SCREEN 0
CLS
COLOR 2
PRINT
PRINT
PRINT "                          Credits:"
PRINT "                          --------"
PRINT
PRINT
PRINT "Graphics:          Nabile El-Isa"
PRINT "Graphic Design:    Nabile El-Isa"
PRINT "Animation:         Nabile El-Isa"
PRINT "Sound:             Nabile El-Isa"
PRINT "Special Effects:   Nabile El-Isa"
PRINT "Theme:             Nabile El-Isa"
PRINT "Programming:       Nabile El-Isa"
PRINT "Licencing:         Nabile El-Isa"
PRINT "Packaging:         Nabile El-Isa"
PRINT "Distributing:      Nabile El-Isa"
PRINT "Anything Else:     Nabile El-Isa"
SLEEP
RUN "c:\nabman\main.bas"



